name: growthpad
description: Society Maintenance Management System

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.1
  shared_preferences: ^2.0.13

  # UI
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  month_picker_dialog: ^0.4.0

  # Firebase
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_messaging: ^11.2.6
  firebase_database: ^9.0.6
  cloud_firestore: ^3.1.8

  # Helper
  connectivity_plus: ^2.2.0
  uuid: ^3.0.5
  pdf: ^3.7.4
  open_file: ^3.2.1
  path_provider: ^2.0.9
  razorpay_flutter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/growthpad.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
